### ISSUE TITLE
Blockly

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/QEdit#8]
- [x] Try to add Blockly.
<s>Make Blockly inject ```code``` into ```$("#desc>.ace_text-input").value``` AND make it take effect in the app. (It takes effect in the DOM (I think).  The console returns the proper value, but it doesn't change inside of the app. (#8 )</s>
- [x] Make a Blockly toggle show up when <s>selecting 'JavaScript' input</s> right-clicking.  (For now, the user can use Blockly, then copy and paste the output into the proper textarea.)
- [x] Create a custom ```msg``` Blockly block. (#14 )
- [x] Add variable blocks. (#16 )
- [x] Fix issue with naming variables in blocks.  (Missing function) (#15 )
- [x] Make one more commit with the current Blockly code (for archival purposes).
- [x] Lose the Blockly stuff in this fork.  (Pixie will set it up much better, anyway, and I don't like it (and don't like messing with it).)

---
Got it "working" in the editor.  (Just need to put it in the right place now.)

<details><summary>OLD INFO</summary>

![image](https://user-images.githubusercontent.com/30656341/103256961-d6843080-4954-11eb-87d7-c23383594cad.png)

---
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta http-equiv="Content-Security-Policy" content="
    default-src 'self';
    style-src 'unsafe-inline' 'self' https://fonts.googleapis.com https://ajax.googleapis.com;
    font-src 'self' https://fonts.gstatic.com;
    script-src 'unsafe-eval' 'unsafe-inline' 'self' https://ajax.googleapis.com https://html5shiv.googlecode.com;
    worker-src blob: https://ajax.googleapis.com;
    img-src 'self' data: https://ajax.googleapis.com;"
  >
  <link rel="stylesheet" href="style/rsuite.css">
  <link rel="stylesheet" href="style/qedit.css">
  
  <script src="../node_modules/blockly/blockly_compressed.js"></script>
  <script src="../node_modules/blockly/blocks_compressed.js"></script>
  <script src="../node_modules/blockly/msg/js/en.js"></script>
  <script src="../node_modules/blockly/javascript_compressed.js"></script>
  <script src="../node_modules/blockly/node.js"></script>
  <head>
<body style="overflow: hidden; margin: auto;" >
  <div id="App"></div>
  <textarea id="textarea"></textarea>
  <div id="blocklyDiv" style="height: 480px; width: 600px;"></div>
  
  <xml id="toolbox" style="display: none">
      <block type="controls_if"></block>
      <block type="controls_repeat_ext"></block>
      <block type="logic_compare"></block>
      <block type="math_number"></block>
      <block type="math_arithmetic"></block>
      <block type="text"></block>
      <block type="text_print"></block>
      <block type="logic_boolean"></block>
    </xml>
</body>

<script type="text/jsx">
  import React from 'react'
  import ReactDOM from 'react-dom'
  import {AppContainer} from 'react-hot-loader'

  const render = () => {
    const App = require('./app').default
    ReactDOM.render(<AppContainer><App /></AppContainer>, document.getElementById('App'))
  }

  render()
  if (module.hot) {
    module.hot.accept(render)
  }

  //Blockly
  const Blockly = require('../node_modules/blockly/node')
  var workspace = Blockly.inject('blocklyDiv',
    {toolbox: document.getElementById('toolbox')});
  function myUpdateFunction(event) {
    var code = Blockly.JavaScript.workspaceToCode(workspace);
    document.getElementById('textarea').value = code;
    console.log(code);
  }
  workspace.addChangeListener(myUpdateFunction);
  //$('#App').appendChild($('#blocklyDiv'))

</script>
</html>
```

</details>

**Comment by KVonGit** [comment]
I foresee an issue with targeting which text input field Blockly is injected code into.

If there are no element ids, I don't know how to do it.  (Are there element ids in the editor?)

**Comment by KVonGit** [comment]
This is was all I really needed:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta http-equiv="Content-Security-Policy" content="
    default-src 'self';
    style-src 'unsafe-inline' 'self' https://fonts.googleapis.com https://ajax.googleapis.com;
    font-src 'self' https://fonts.gstatic.com;
    script-src 'unsafe-eval' 'unsafe-inline' 'self' https://ajax.googleapis.com https://html5shiv.googlecode.com;
    worker-src blob: https://ajax.googleapis.com;
    img-src 'self' data: https://ajax.googleapis.com https://blockly-demo.appspot.com;
    media-src 'self' data: https://blockly-demo.appspot.com;"
  >
  <link rel="stylesheet" href="style/rsuite.css">
  <link rel="stylesheet" href="style/qedit.css">
<head>
<body style="overflow: hidden; margin: auto;" >
  <div id="App"></div>
  <textarea id="textarea"></textarea>
  <div id="blocklyDiv" style="height: 480px; width: 600px;"></div>
  
  <xml id="toolbox" style="display: none">
      <block type="controls_if"></block>
      <block type="controls_repeat_ext"></block>
      <block type="logic_compare"></block>
      <block type="math_number"></block>
      <block type="math_arithmetic"></block>
      <block type="text"></block>
      <block type="text_print"></block>
      <block type="logic_boolean"></block>
    </xml>
</body>

<script type="text/jsx">
  import React from 'react'
  import ReactDOM from 'react-dom'
  import {AppContainer} from 'react-hot-loader'

  const render = () => {
    const App = require('./app').default
    ReactDOM.render(<AppContainer><App /></AppContainer>, document.getElementById('App'))
  }

  render()
  if (module.hot) {
    module.hot.accept(render)
  }

  //Blockly
  const Blockly = require('../node_modules/blockly/node')
  var workspace = Blockly.inject('blocklyDiv',
    {toolbox: document.getElementById('toolbox')});
  function myUpdateFunction(event) {
    var code = Blockly.JavaScript.workspaceToCode(workspace);
    document.getElementById('textarea').value = code;
    console.log(code);
  }
  workspace.addChangeListener(myUpdateFunction);
  //$('#App').appendChild($('#blocklyDiv'))

</script>
</html>
```

**Comment by KVonGit** [comment]
It won't let me change the value of the textarea on an object.  I think this is the code that sets that element up:

```js
import React from 'react'
import { FormGroup, SelectPicker, ControlLabel, HelpBlock } from 'rsuite'
import AceEditor from "react-ace"
import * as Constants from '../constants'

// Fixes bug in ace-builds, where it can't find the worker
const ace = require('ace-builds/src-noconflict/ace')
ace.config.set("basePath", __dirname + "/../../node_modules/ace-builds/src-noconflict/")

const data = [
  Constants.MSG_OPTION,
  Constants.JS_OPTION,
  Constants.ASL_OPTION].map((s, i) => {return({value: s, label: s})})

export default class ScriptString extends React.Component {
/*  constructor(props) {
    super(props)
    this.handleChangeType = this.handleChangeType.bind(this)
  }

  handleChangeType(newValue) {
    const {objects, item} = this.props
    const type = {}

    switch (newValue) {
      case Constants.JS_OPTION:
        type.type = Constants.JS_TYPE
        break
      case Constants.ASL_OPTION:
        type.type = Constants.ASL_TYPE
        break
      case Constants.MSG_OPTION:
        type.type = Constants.MSG_TYPE
        break
    }

    objects.setScript(item.name, type)
  }
*/
  render() {
    const {item, objects} = this.props
    const value = objects.getValue(item.name) || item.default
    const {code} = value
    const type = value.type || Constants.DEFAULT_TYPE
    const option = Constants.SCRIPT_OPTION[type]
    const mode = Constants.SCRIPT_MODE[type]
/*
    var option, mode

    switch (type) {
      case Constants.JS_TYPE:
        option = Constants.JS_OPTION
        mode = Constants.JS_MODE
        break
      case Constants.ASL_TYPE:
        option = Constants.ASL_OPTION
        mode = Constants.ASL_MODE
        break
      case Constants.MSG_TYPE:
        option = Constants.MSG_OPTION
        mode = Constants.MSG_MODE
        break
    }
*/
    return (
      <FormGroup>
        <ControlLabel>{item.display}:</ControlLabel>
        <SelectPicker
          key={item.name + '_option'}
          style={Constants.INPUTCOMPONENT_STYLE}
          data={data}
          defaultValue={option}
          onChange={(v) =>
            objects.setScript(item.name, {type:Constants.SCRIPT_TYPE[v]})}
          cleanable={false}
        />
        <br/>
        <AceEditor
          mode={mode}
          theme={Constants.ACETHEME}
          onChange={(v) => objects.setScript(item.name, {code:v})}
          name={item.name}
          editorProps={{ $blockScrolling: true }}
          value={code}
          style={Constants.ACE_STYLE}
        />
        {item.tooltip ? <HelpBlock tooltip>{item.tooltip}</HelpBlock> : ''}
      </FormGroup>
    )
  }
}
```

**Comment by KVonGit** [comment]
@ThePix

I need help.

I don't know how to adjust the CSS to put the blockly div to the left of the existing textarea.

I also don't know how to use JS to change the value of the existing textarea.  (It seems like it works in the console, but the changes don't show up in the textarea in the app.  The textarea's value returns what I just set it to, but it just doesn't seem to work in the app.)

https://user-images.githubusercontent.com/30656341/103289925-fc89ef00-49ad-11eb-9e1b-877bec89ff58.mp4


---
Also, I can't seem to access the ```document``` from within the code I added to 'Preferences'.

```js
            <FormGroup>
              <ControlLabel>Blockly:</ControlLabel>
              <Toggle
                key="Blockly"
                defaultChecked={false}
                onChange={(value) => {
                    document.getElementsByTagName('body')[0].style.overflow = value ? 'auto' : 'hidden';
                    
                  }
                }
                style={{marginTop:5}}
              />
            </FormGroup>
```

---
That ```onChange``` doesn't do anything in the app.

I wanted it to allow us to scroll down to use Blockly in the app, then copy and paste the code.  (Not permanently.  Just to have it kind of functional.)

I can do that by changing the display setting on the body to auto from the console.  Here's what the "Blockly action" looks like:


https://user-images.githubusercontent.com/30656341/103290559-766ea800-49af-11eb-825d-cc8f7640850e.mp4

**Comment by KVonGit** [comment]
> Also, I can't seem to access the document from within the code I added to 'Preferences'.

Duh.

I had to use ```window.document```, not ```document```.

**Comment by KVonGit** [comment]
Oh, snap!

I think I've got it!  (Halfway.)

https://user-images.githubusercontent.com/30656341/103294302-3d3a3600-49b7-11eb-8b5f-7da10b5adccd.mp4

**Comment by KVonGit** [comment]
I'm going to attempt to make that Blockly switch only show up when it's on 'Javascript', but I make no promises.

I also still need to figure out how to make the Ace editor set the value passed from Blockly.

**Comment by KVonGit** [comment]
It seems that altering the tab broke the save feature.

More on this as it comes in . . .

**Comment by KVonGit** [comment]
```
Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>.
    in form (created by Form)
    in Form (created by ScriptString)
    in ScriptString (created by ControlPane)
    in form (created by Form)
    in Form (created by ControlPane)
    in ControlPane (created by TabPane)
    in div (created by Content)

. . .
```

**Comment by KVonGit** [comment]
> It seems that altering the tab broke the save feature.

No.  I broke the save feature in a different bit of code.  Fixed now, though.

**Comment by KVonGit** [comment]
Now, right-clicking gives the option to display Blockly at the bottom of the page.

You have to copy your code from Blockly's output textarea and paste it into the Javascript text area.  (I finally got it to directly update the value of the Javascript textarea, but it made the editor go crazy behind the scenes.  Plus, you had to manually hit ENTER to get the code to take.)

**Comment by KVonGit** [comment]
I just removed Blockly before the last commit (just now).

If you want this with a crappy version of Blockly in it (if just to view the code, which is mostly in "blocks.js"), it is here:

https://github.com/KVonGit/QEdit/releases/tag/v0.0.7

---
Note that I was using Blockly, not node-blockly, and I was targeting the "node.js" file inside the blockly directory in node_modules.
